### ISSUE TITLE
Filtering on geographical places should consider the geonames hierarchy

### ISSUE THREAD

**Issue by rtroncy** [silknow/adasilk#2]
Selecting the objects produced in France and coming from the Joconde museum yields [0 result](https://ada.silknow.org/browse?type=object&field_filter_location=https%3A%2F%2Fsws.geonames.org%2F3017382%2F&graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Fjoconde) which is obviously wrong.

This [item](https://ada.silknow.org/object/329ae1a1-f6a1-3e5b-91f5-5336512f1d80) should for example be retrieved. It has Saint Etienne as production place which is within France. The hierarchy needs to be climbed.

**Comment by ehrhart** [comment]
Based on the facet page of [Saint-Etienne](https://data.silknow.org/describe/?url=https%3A%2F%2Fsws.geonames.org%2F2980291%2F), it looks like we should check for the value of `geonames:parentCountry`.

**Comment by rtroncy** [comment]
Right! The API also always returns the country level in addition to potentially a more fine grained geo information (e.g. city). We have indeed materialized in the KG the country level information systematically.

**Comment by ehrhart** [comment]
The query has been updated. Your selection now yields [371 results](https://ada.silknow.org/browse?type=object&field_filter_location=https%3A%2F%2Fsws.geonames.org%2F3017382%2F&graph=http%3A%2F%2Fdata.silknow.org%2Fgraph%2Fjoconde&page=1)

**Comment by rtroncy** [comment]
Should we close this issue @ehrhart ?
