### ISSUE TITLE
The image rights should be displayed under the image rather than on overlay

### ISSUE THREAD

**Issue by rtroncy** [silknow/adasilk#3]
Example: https://ada.silknow.org/object/329ae1a1-f6a1-3e5b-91f5-5336512f1d80

The right of this image seems to be http://data.silknow.org/object/329ae1a1-f6a1-3e5b-91f5-5336512f1d80/right : "propriété de la commune (fr)"

It should be displayed under the image and not as an overlay on the image.

@tschleider given the URI pattern used, it seems that the rights is attached to the object rather than the image. Is it intended? 
I think we should check as we could have rights attached to the entire record (D1) / or attached to the images.

**Comment by ehrhart** [comment]
The image rights are now displayed under the image.

Regarding the KG question I suggest that we open an issue on [silknow/converter](https://github.com/silknow/converter) if it requires an action.
