### ISSUE TITLE
Error when deleting the search text

### ISSUE THREAD

**Issue by pasqLisena** [silknow/adasilk#6]
On the homepage, when you write anything in the main search field and then delete it, the page disappears and is replaced by

    An error occurred on client

**Comment by ehrhart** [comment]
Fixed by https://github.com/D2KLab/explorer/commit/634102d874fb2f467386439f4977903e88129954

Explanation: autocompletion uses `bif:contains` which requires keywords of more than 3 characters. If the keyword is shorter then it will return an error.
